name: CI Tests

on:
  push:
    branches: [ main ]

jobs:

  presubmit:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build github.com/downflux/go-flowfield
      run: go build github.com/downflux/go-flowfield/...

    - name: Build github.com/downflux/go-flowfield
      run: go vet github.com/downflux/go-flowfield/...

    - name: Test github.com/downflux/go-flowfield
      run: go test github.com/downflux/go-flowfield/... -run ^$ -bench . -benchmem
