name: CI Presubmits

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ "*" ]

jobs:

  presubmit:
    name: CI Presubmits
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.3

    - name: Test github.com/downflux/go-flowfield
      run: go test github.com/downflux/go-flowfield/...
